### ISSUE TITLE
[Feature Request] Deltas for 3 hidden statistics

### ISSUE THREAD

**Issue by cookieMr** [konradkalemba/korona.ws#72]
I can see deltas for deaths, infections and cured people. How about the same deltas for other 3 (hidden) statistics (hospitalised, quarantined and the 3rd long one).

Such feature is offen requested ([or provided in comments](https://twitter.com/MarchelPiotr/status/1251773072845258752)) on "Ministerstwo Zdrowia" twitter.

**Comment by konradkalemba** [comment]
This is implemented and was working till MZ omitted one day and didn't provide a daily report, which was sent the following morning. I decided then to link the changes in figures with previous day. And I've been doing like that since then. However I think I'll change my approach and link it with the day the report was published starting tomorrow.
